<?php

namespace PanelBundle\Repository;

/**
 * AnkietaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnkietaRepository extends \Doctrine\ORM\EntityRepository
{
}
