<?php

namespace PanelBundle\Repository;

/**
 * imieNazwiskoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class imieNazwiskoRepository extends \Doctrine\ORM\EntityRepository
{
}
