<?php

namespace PanelBundle\Repository;

/**
 * OdpowiedziRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OdpowiedziRepository extends \Doctrine\ORM\EntityRepository
{
}
