<?php

namespace PanelBundle\Repository;

/**
 * PytanieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PytanieRepository extends \Doctrine\ORM\EntityRepository
{
}
